### ISSUE TITLE
Ingredient.java final fields are not initialized

### ISSUE THREAD

**Issue by aCodeRancher** [habuma/spring-in-action-5-samples#2]
The id, name, type of the Ingredient class are not initialized.

**Comment by habuma** [comment]
This issue and many of the others you've reported seem to be because you didn't notice that I'm using Lombok to handle boilerplate code like getters, setters, constructors, etc, etc.

If you are building the projects from the command line and are getting errors such as these, then please let me know which chapter you're getting the errors in and I can take a look. If you are importing the code into your IDE, you'll need to have Lombok installed in your IDE (see https://projectlombok.org/ for details). That said, I would agree that the README file(s) should mention Lombok and point you to instructions for installing it in your IDE.

I've created a new issue, #21,  for the README work, but consider this one closed. You may reopen it if you do not feel it adequately addressed.
