### ISSUE TITLE
Chapter 4. Set Role problem

### ISSUE THREAD

**Issue by yeyypp** [habuma/spring-in-action-5-samples#55]
When set the role with `hasRole("ROLE_USER")` as the book said
It got 

> java.lang.IllegalArgumentException: role should not start with 'ROLE_' since it is automatically inserted.

I changed it to 
`hasRole("USER")` 
and 
```
@Override  
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Arrays.asList(new SimpleGrantedAuthority("USER"));
    }
```
It can get access to "/login" and "/register" but got forbidden of "/design" even when I already successful login.

**Comment by e90r** [comment]
did you get the understanding of why this problem appeared? got same issue, too

**Comment by cnwachukwu5** [comment]
***The solution***:

In the getAuthorities() of the User.java class, do not change "ROLE_USER" to "USER".

***Expanation***:
When you call method hasRole("ROLE_USER"), Spring Security automatically prefixes roles with "ROLE_", hence the exception. This is resolved by removing the "ROLE_" prefix in the hasRole() invocation. However, do not change the "ROLE_USER" in the getAuthorities() method in the User.java to "USER", this will cause the HTTP 403 error. 

This is because when the application starts, if you look at the logs (**enable spring security logging by adding logging.level.org.springframework.security=debug to application.properties**), you will see a log entry ****"_Adding web access control expression [hasRole('ROLE_USER')] for Ant [pattern='/design']_****, this implies that User must have "ROLE_USER" to access the /design path. By changing the getAuthorities() to "USER", created users will have authority of "USER" not "ROLE_USER" that Spring Security has configured for that path. 

Another solution will be to change the "ROLE_USER" in the getAuthorities() method to "USER",  and make a call to hasAuthority("USER") instead of hasRole("USER").

Hope this helps somebody!!

**Comment by cnwachukwu5** [comment]
I also observed that after completing the design Taco form and submitting it to go to /orders, I get HTTP 403 error. I fixed it by

- the antMatchers("/design", "/orders") should be changed to antMatchers("/design", "/orders/**"). This is because the call to display the order is /orders/current.
- add the csrf token hidden field `**_(<input type="hidden" name="_csrf" th:value="${_csrf.token}"/>)_**` to your design and order form. This helps the Spring Security to validate csrf token when you submit the form
