### ISSUE TITLE
Chapter 3 - Conversion error when selecting ingredient in design for and submitting

### ISSUE THREAD

**Issue by mananmehta11** [habuma/spring-in-action-5-samples#70]
Failed to convert property value of type java.lang.String[] to required type java.util.List for property ingredients; nested exception is java.lang.IllegalStateException: Cannot convert value of type java.lang.String to required type tacos.Ingredient for property ingredients[0]: no matching editors or conversion strategy found

**Comment by mananmehta11** [comment]
Add IngredientByIdConverter refer tacos.web package.

**Comment by rnaveen93** [comment]
I added IngredientByIdConverter  class to tacos.web package but still recieving  
`2020-04-11 23:16:15.035 ERROR 75144 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaSystemException: Error accessing field [private java.lang.String tacos.Ingredient.id] by reflection for persistent property [tacos.Ingredient#id] : FLTO; nested exception is org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [private java.lang.String tacos.Ingredient.id] by reflection for persistent property [tacos.Ingredient#id] : FLTO] with root cause

java.lang.IllegalArgumentException: Can not set java.lang.String field tacos.Ingredient.id to java.lang.String
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[na:1.8.0_241]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source) ~[na:1.8.0_241]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source) ~[na:1.8.0_241]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(Unknown Source) ~[na:1.8.0_241]`
